In [1]:
# Numpy stands for numerical python
# It can only have homogenous data in it (i.e all element have thr same datatype)

In [4]:
!pip install numpy

In [5]:
import numpy as np
print('package successfully imported')

package successfully imported


In [10]:
# Creating 1D array from a list

list_var = [1, 2, 3, 4, 5]
print(type(list_var))

print(list_var, end ='\n\n')
# To convert list to an array, we use array function
list_to_array = np.array(list_var)
print(list_to_array)
print(type(list_to_array))

<class 'list'>
[1, 2, 3, 4, 5]

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [15]:
# Creating 1D array from a tuple
tuple_var = (1, 2, 3, 4, 5) 
tuple_to_array = np.array(tuple_var)
print(type(tuple_var))
print(tuple_var)
print(type(tuple_to_array))
print(tuple_to_array)

<class 'tuple'>
(1, 2, 3, 4, 5)
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [17]:
# homogenous data
# decimals has greater order than the whole numbers

list_var = [1, 2, 3, 4, 5.5, 6.0]
print(list_var)
list_to_array = np.array(list_var)
print(list_to_array)
print(type(list_var))
print(type(list_to_array))

[1, 2, 3, 4, 5.5, 6.0]
[1.  2.  3.  4.  5.5 6. ]
<class 'list'>
<class 'numpy.ndarray'>


In [18]:
# String data type has the greater oorder than decimal and whole numbers
list_var = [1, 2, 3, 4, 5.5, 6.0, 'e']
print(list_var)
list_to_array = np.array(list_var)
print(list_to_array)
print(type(list_var))
print(type(list_to_array))

[1, 2, 3, 4, 5.5, 6.0, 'e']
['1' '2' '3' '4' '5.5' '6.0' 'e']
<class 'list'>
<class 'numpy.ndarray'>


# Dimensions in arrays

In [28]:
# Multiple 1D array make a 2D array
array_2d = np.array([[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]])
print("array 2D: ", array_2d, sep='\n\n')

array 2D: 

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [37]:
# Multiple 2D array make a 3D array
array_3d = np.array([[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]], [[10, 11, 12],[7, 8, 9]]])
print("array_3d",array_3d, sep='\n\n')

array_3d

[[[ 5.2  3.   4.5]
  [ 9.1  0.1  0.3]]

 [[10.  11.  12. ]
  [ 7.   8.   9. ]]]


In [ ]:
07032731313

# How Numpy is better

Q. Add each list element index to index and create a new list.
1. list_1 = [1, 2, 3, 4, 5]
2. list_2 = [6, 7, 8, 9, 10]

In [42]:
list_1 = [1, 2, 3, 4, 5, 6]
list_2 = [6, 7, 8, 9, 10, 10]
sum_list = []
length_1 = len(list_1)
length_2 = len(list_2)
min_length = min(length_1, length_2)

for i in range(0, min_length):
    sum_list.append(list_1[i] + list_2[i])
print(sum_list)

[7, 9, 11, 13, 15, 16]


In [44]:
list_1 = [1, 2, 3, 4, 5, 6]
list_2 = [6, 7, 8, 9, 10, 10]
sum_list = list(map(lambda x, y : x + y, list_1 , list_2))
print(sum_list)

[7, 9, 11, 13, 15, 16]


In [46]:
# You can easily solve list additions using numpy
list_1 = [1, 2, 3, 4, 5, 6]
list_2 = [6, 7, 8, 9, 10, 10]
array_1 = np.array(list_1)
array_2 = np.array(list_2)
sum_list = array_1 + array_2
print(sum_list)

[ 7  9 11 13 15 16]


In [49]:
 array_1_bool = array_1 >= 3
print("Checking for the condition", array_1_bool, end='\n\n')
print("What are the values that satisfy the condition", array_1[array_1_bool])

Checking for the condition [False False  True  True  True  True]

What are the values that satisfy the condition [3 4 5 6]


In [50]:
# Simplifying the above cloud
array_1[array_1 > 2]

array([3, 4, 5, 6])

In [62]:
# Adding 2d arrays
list_1 = [[1, 2, 3], [4, 5, 6]]
list_2 = [[11, 12, 13], [14, 15, 16]]

arr_1 = np.array(list_1)
arr_2 = np.array(list_2)
print("First array: \n", arr_1, end ='\n\n')
print("Second array: \n", arr_2, end= '\n\n')
print("Final array: \n", arr_1 + arr_2, end='\n\n')

First array: 
 [[1 2 3]
 [4 5 6]]

Second array: 
 [[11 12 13]
 [14 15 16]]

Final array: 
 [[12 14 16]
 [18 20 22]]



# Numpy Functions

## Arrange Functions

In [68]:
# Arrange functions, (increment factor) spelt as arange
arange_array = np.array(list(range(1, 15, 2)))
print("Using complex nested  function:\n", arange_array, end='\n\n')

arange_array = np.arange(1, 15, 2)
print("Using simple numpy function:\n", arange_array)

Using complex nested  function:
 [ 1  3  5  7  9 11 13]

Using simple numpy function:
 [ 1  3  5  7  9 11 13]


In [69]:
# Arrange functions, (decreament factor) spelt as arange

arrange_array = np.arange(15, 0, -2)
print(arrange_array)

[15 13 11  9  7  5  3  1]


In [79]:
zero_array_1d = np.zeros((5), dtype = int)
print("1D array:\n", zero_array_1d)

zero_array_2d = np.zeros((5, 5), dtype= int)
print("2D array:\n", zero_array_2d, sep='\n')

1D array:
 [0 0 0 0 0]
2D array:

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [82]:
one_array_1d = np.ones(5)
print("1D array:\n", one_array_1d)

one_array_2d = np.ones((5, 5), dtype= int)
print("2D array:\n", one_array_2d, sep = '')

1D array:
 [1. 1. 1. 1. 1.]
2D array:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [8]:
import numpy as np
zero_array_2d = np.zeros((5, 5), dtype =int)
print(zero_array_2d)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [10]:
one_array_2d = np.ones((6, 6), dtype=int)
print(one_array_2d)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [11]:
# Instead of having zeros and ones in the array.
# we can also have an array of numbers other than zeros and ones
# The function called np.full(shape= "", fill_value=" ")

In [23]:
print(np.full(shape= 5,fill_value = 5),end ="\n\n")
print(np.full(shape=(5, 5), dtype=int, fill_value=3))

[5 5 5 5 5]

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [26]:
# Sometimes you need random values
np.random.random((3, 3))

array([[0.20886456, 0.90642778, 0.76560256],
       [0.85574242, 0.7989264 , 0.36634587],
       [0.67738052, 0.29345814, 0.16715695]])

In [46]:
# Random.randint and random.seed significance
np.random.seed(2)
print(np.random.randint(low = 1,high = 15, size = 10))
np.random.randint(low=1,high=15,size=(3,3))

[ 9 14  9  7 12  3 12  9  8  3]


array([[ 2, 12,  6],
       [11,  5, 13],
       [ 5,  6,  8]])

In [36]:
print(np.random.randint(low = 1,high = 15, size = 10))

[ 2 13  4  2  4  7  8 11  5  1]


In [40]:
np.random.randint(low=1,high=15,size=(3,3))

array([[11,  9,  3],
       [14, 14,  5],
       [14,  3,  4]])

In [47]:
# Identity matrix
# Important
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [48]:
# Generally, and identity matrix is a square matrix
# we could change the order
np.eye(N = 3, M = 5, dtype= int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [58]:
# linspace is used when the size  and the range of the output is known but the stepsize is not known
arr_1 = np.linspace(1, 40, 15, dtype= int)
print(arr_1)
arr_1.shape

[ 1  3  6  9 12 14 17 20 23 26 28 31 34 37 40]


(15,)

In [62]:
np.linspace(1, 40, 6, dtype= int).reshape(2, 3)

array([[ 1,  8, 16],
       [24, 32, 40]])

In [63]:
np.tile([1, 2, 3], 2)

array([1, 2, 3, 1, 2, 3])

In [65]:
print("2D: \n",np.tile([1, 2, 3], (3, 3)))

2D: 
 [[1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]]


In [90]:
arr_1 = np.tile([1, 2, 3], (3,1))
print("arr_1: \n",arr_1, end ="\n\n")

arr_2 = np.arange(2, 20, 2).reshape(3, 3)
print("arr_2: \n",arr_2, end ="\n\n")

new_arr = arr_1 + arr_2
print("New arr: \n",new_arr)

arr_1: 
 [[1 2 3]
 [1 2 3]
 [1 2 3]]

arr_2: 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

New arr: 
 [[ 3  6  9]
 [ 9 12 15]
 [15 18 21]]


In [94]:
np.linspace(2, 20, 9, dtype=int).reshape(3, 3)

array([[ 2,  4,  6],
       [ 8, 11, 13],
       [15, 17, 20]])

# Structure

In [102]:
array = np.tile([1, 2, 3], (3, 1))
print(array, end="\n\n")
print("Data type:", array.dtype)
print("Data shape:", array.shape)
print("Data number of dimension:", array.ndim)

[[1 2 3]
 [1 2 3]
 [1 2 3]]

Data type: int32
Data shape: (3, 3)
Data number of dimension: 2


In [108]:
# Indexing, subsetting and slicing
print("First row:", array[1])
print("Zeroth element: ", array[1][0])
print("Zeroth element: ", array[1,0])
print("First 2 element:", array[1,:2])
print("Reverse of the first row:", array[1,::-1])

First row: [1 2 3]
Zeroth element:  1
Zeroth element:  1
First 2 element: [1 2]
Reverse of the first row: [3 2 1]


In [126]:
import time
start_time = time.time()

end_time = time.time()
time = end_time - start_time
print(time)

0.0


In [3]:
import numpy as np

In [10]:
# For matrix product, the @ operator can be used of A.dot(B) can also be used
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

A @ B


array([[5, 4],
       [3, 4]])

In [11]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [25]:
# Some operator += and *= act in place to modify an existing array rather than create a new one

rg = np.random.default_rng(1)
print(rg)
print()
a = np.ones((2, 3), dtype = int)
print(a)
print()
b = rg.random((2, 3))
print(b)
a += 3
a

Generator(PCG64)

[[1 1 1]
 [1 1 1]]

[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]


array([[4, 4, 4],
       [4, 4, 4]])